version: '3.9'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  metabase:
    image: metabase/metabase
    container_name: metabase
    ports:
      - "3500:3500"
    environment:
      - MB_DB_TYPE=mysql
      - MB_DB_DBNAME=${MYSQL_DATABASE}
      - MB_DB_PORT=${MYSQL_PORT}
      - MB_DB_USER=${MYSQL_USER}
      - MB_DB_PASS=${MYSQL_PASSWORD}
      - MB_DB_HOST=${MYSQL_HOST}
    depends_on:
      - mysql

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    ports:
      - '4100:4100'
    environment:
      - PORT=4100
      - MONGODB_URI=${MONGODB_URI}
      - NODE_ENV=${NODE_ENV}

  user-service:
    build:
      context: ./user-service
    container_name: user-service
    ports:
      - '4200:4200'
    environment:
      - PORT=4200
      - MONGODB_URI=${MONGODB_URI}
      - NODE_ENV=${NODE_ENV}
      - CORS_ORIGIN=${CORS_ORIGIN}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ALGORITHM=${JWT_ALGORITHM}
      - REDIS_URL=${REDIS_URL}

  product-service:
    build:
      context: ./product-service
    container_name: product-service
    ports:
      - '4300:4300'
    environment:
      - PORT=4300
      - MONGODB_URI=${MONGODB_URI}
      - NODE_ENV=${NODE_ENV}
      - CORS_ORIGIN=${CORS_ORIGIN}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ALGORITHM=${JWT_ALGORITHM}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - REDIS_URL=${REDIS_URL}

  cart-service:
    build:
      context: ./cart-service
    container_name: cart-service
    ports:
      - '4400:4400'
    environment:
      - PORT=4400
      - MONGODB_URI=${MONGODB_URI}
      - NODE_ENV=${NODE_ENV}
      - CORS_ORIGIN=${CORS_ORIGIN}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ALGORITHM=${JWT_ALGORITHM}
      - TAX_RATE=${TAX_RATE}

  payment-service:
    build:
      context: ./payment-service
    container_name: payment-service
    ports:
      - '4500:4500'
    environment:
      - PORT=4500
      - MONGODB_URI=${MONGODB_URI}
      - NODE_ENV=${NODE_ENV}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ALGORITHM=${JWT_ALGORITHM}
      - TAX_RATE=${TAX_RATE}

  order-service:
    build:
      context: ./order-service
    container_name: order-service
    ports:
      - '4600:4600'
    environment:
      - PORT=4600
      - MONGODB_URI=${MONGODB_URI}
      - NODE_ENV=${NODE_ENV}
      - CORS_ORIGIN=${CORS_ORIGIN}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ALGORITHM=${JWT_ALGORITHM}
      - PAYMENTS_SERVICE_TOKEN=${PAYMENTS_SERVICE_TOKEN}

  analytics-service:
    build:
      context: ./analytics-service
    container_name: analytics-service
    ports:
      - '4700:4700'
    depends_on:
      - mysql
    environment:
      - PORT=4700
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DB=${MYSQL_DB}
      - ORDER_SERVICE_HOST=${ORDER_SERVICE_HOST}
      - JWT_SECRET=${JWT_SECRET}
      - ORDER_SERVICE_TOKEN=${ORDER_SERVICE_TOKEN}
      - DIALECT=${DIALECT}

  gateway:
    build:
      context: ./gateway
    container_name: gateway
    ports:
      - '8080:8080'
    depends_on:
      - auth-service
      - user-service
      - product-service
      - cart-service
      - payment-service
      - order-service
      - analytics-service
    environment:
      - NODE_ENV=${NODE_ENV}
      - AUTH_SERVICE_HOST=${AUTH_SERVICE_HOST}
      - USER_SERVICE_HOST=${USER_SERVICE_HOST}
      - PRODUCT_SERVICE_HOST=${PRODUCT_SERVICE_HOST}
      - CART_SERVICE_HOST=${CART_SERVICE_HOST}
      - PAYMENT_SERVICE_HOST=${PAYMENT_SERVICE_HOST}
      - ORDER_SERVICE_HOST=${ORDER_SERVICE_HOST}
      - ANALYTICS_SERVICE_HOST=${ANALYTICS_SERVICE_HOST}

volumes:
  mongo_data:
  mysql_data:
  redis_data:
