http:
  port: 8080 

admin:
  port: 9876
  host: localhost

apiEndpoints:
  auth:
    pathRegex: "/api/auth.*" 
    host: "*"
  user:
    pathRegex: "/api/user.*" 
    host: "*"
  product:
    pathRegex: "/api/product.*" 
    host: "*"
  cart:
    pathRegex: "/api/cart.*" 
    host: "*"  
  order:
    pathRegex: "/api/order.*" 
    host: "*"
  payment:
    pathRegex: "/api/payment.*" 
    host: "*"
  analytics:
    pathRegex: "/api/analytics.*" 
    host: "*"

serviceEndpoints:
  auth-service:
    url: https://auth-service-vk7z.onrender.com/ 
  user-service:
    url: https://user-service-o164.onrender.com/ 
  product-service:
    url: https://product-service-o0qc.onrender.com/ 
  cart-service:
    url: https://cart-service-nlid.onrender.com/
  payment-service:
    url: https://payment-service-jtgg.onrender.com/
  order-service:
    url: https://order-service-i1yb.onrender.com/
  analytics-service:
    url: https://analytics-service-7ntq.onrender.com/


policies:
  - cors
  - rate-limit
  - proxy

pipelines:
  auth-pipeline:
    apiEndpoints:
      - auth
    policies:
      - cors:
          - action:
              origin: "*"
              methods: "GET,POST,PUT,DELETE"
      - rate-limit:
          - action:
              max: 100
              windowMs: 60000
              rateLimitBy: "${req.ip}"
              message: "Too many requests from this IP, please try again later."
      - proxy:
          - action:
              serviceEndpoint: auth-service
              changeOrigin: true
  user-pipeline:
    apiEndpoints:
      - user
    policies:
      - cors:
          - action:
              origin: "*"
              methods: "GET,POST,PUT,DELETE"
      - proxy:
          - action:
              serviceEndpoint: user-service
              changeOrigin: true
  product-pipeline:
    apiEndpoints:
      - product
    policies:
      - cors:
          - action:
              origin: "*"
              methods: "GET,POST,PUT,DELETE"
      - proxy:
          - action:
              serviceEndpoint: product-service
              changeOrigin: true
  cart-pipeline:
    apiEndpoints:
      - cart
    policies:
      - cors:
          - action:
              origin: "*"
              methods: "GET,POST,PUT,DELETE"
      - proxy:
          - action:
              serviceEndpoint: cart-service
              changeOrigin: true
  order-pipeline:
    apiEndpoints:
      - order
    policies:
      - cors:
          - action:
              origin: "*"
              methods: "GET,POST,PUT,DELETE"  
      - proxy:
          - action:
              serviceEndpoint: order-service
              changeOrigin: true
  payment-pipeline:
    apiEndpoints:
      - payment
    policies:
      - cors:
          - action:
              origin: "*"
              methods: "GET,POST,PUT,DELETE"  
      - proxy:
          - action:
              serviceEndpoint: payment-service
              changeOrigin: true
  analytics-pipeline:
    apiEndpoints:
      - analytics
    policies:
      - cors:
          - action:
              origin: "*"
              methods: "GET,POST,PUT,DELETE"  
      - proxy:
          - action:
              serviceEndpoint: analytics-service
              changeOrigin: true
  
