http:
  port: ${PORT} # container port

admin:
  port: 9876
  host: localhost

apiEndpoints:
  product:
    pathRegex: "/api/product/.*" 
    host: "*"

serviceEndpoints:
  product-service:
    url: http://localhost:4000/

policies:
  - cors
  - proxy

pipelines:
  product-pipeline:
    apiEndpoints:
      - product
    policies:
      - cors:
          - action:
              origin: "*"
              methods: "GET,POST,PUT,DELETE"
      - proxy:
          - action:
              serviceEndpoint: product-service
              changeOrigin: true

  
