############################################################
# EXPRESS-GATEWAY CONFIG – ONE PUBLIC ENTRYPOINT           #
############################################################

http:
  port: 8080

admin:
  port: 9876
  host: localhost                             # keep admin UI private

# ───────────────────────────────────────────
#  API ENDPOINTS THE GATEWAY LISTENS FOR
# ───────────────────────────────────────────
apiEndpoints:
  auth:      { pathRegex: "^/api/auth.*"      }
  user:      { pathRegex: "^/api/user.*"      }
  product:   { pathRegex: "^/api/product.*"   }
  cart:      { pathRegex: "^/api/cart.*"      }
  order:     { pathRegex: "^/api/order.*"     }
  payment:   { pathRegex: "^/api/payment.*"   }
  analytics: { pathRegex: "^/api/analytics.*" }

# ───────────────────────────────────────────
#  INTERNAL DESTINATIONS (Railway private DNS)
# ───────────────────────────────────────────
serviceEndpoints:
  auth-service:      { url: ${AUTH_SERVICE_HOST} }
  user-service:      { url: ${USER_SERVICE_HOST} }
  product-service:   { url: ${PRODUCT_SERVICE_HOST} }
  cart-service:      { url: ${CART_SERVICE_HOST} }
  payment-service:   { url: ${PAYMENT_SERVICE_HOST} }
  order-service:     { url: ${ORDER_SERVICE_HOST} }
  analytics-service: { url: ${ANALYTICS_SERVICE_HOST} }

# ───────────────────────────────────────────
#  GATEWAY-WIDE POLICY LIST
# ───────────────────────────────────────────
policies:
  - cors
  - rate-limit
  - proxy

# ───────────────────────────────────────────
#  CORS SETTINGS (reuse in every pipeline)
# ───────────────────────────────────────────
cors-default-action: &corsSettings
  origin:        ${CORS_ORIGIN}               # → https://shopsphereg11.netlify.app
  methods:       "GET,POST,PUT,PATCH,DELETE,OPTIONS"
  allowHeaders:  "Content-Type, Authorization"
  credentials:   true

# ───────────────────────────────────────────
#  PROXY SETTINGS (reuse in every pipeline)
# ───────────────────────────────────────────
proxy-default: &proxySettings
  changeOrigin:  true
  headers:
    X-Forwarded-Proto: "https"                # avoids 30x redirects to *.up.railway.app

# ───────────────────────────────────────────
#  PIPELINES
# ───────────────────────────────────────────

pipelines:

  auth-pipeline:
    apiEndpoints: [auth]
    policies:
      - cors:  [ { action: *corsSettings } ]
      - rate-limit:
          - action:
              max: 100
              windowMs: 60000
              rateLimitBy: "${req.ip}"
              message: "Too many requests from this IP, try again later."
      - proxy:
          - action:
              <<: *proxySettings
              serviceEndpoint: auth-service

  user-pipeline:
    apiEndpoints: [user]
    policies:
      - cors:  [ { action: *corsSettings } ]
      - proxy:
          - action:
              <<: *proxySettings
              serviceEndpoint: user-service

  product-pipeline:
    apiEndpoints: [product]
    policies:
      - cors:  [ { action: *corsSettings } ]
      - proxy:
          - action:
              <<: *proxySettings
              serviceEndpoint: product-service

  cart-pipeline:
    apiEndpoints: [cart]
    policies:
      - cors:  [ { action: *corsSettings } ]
      - proxy:
          - action:
              <<: *proxySettings
              serviceEndpoint: cart-service

  order-pipeline:
    apiEndpoints: [order]
    policies:
      - cors:  [ { action: *corsSettings } ]
      - proxy:
          - action:
              <<: *proxySettings
              serviceEndpoint: order-service

  payment-pipeline:
    apiEndpoints: [payment]
    policies:
      - cors:  [ { action: *corsSettings } ]
      - proxy:
          - action:
              <<: *proxySettings
              serviceEndpoint: payment-service

  analytics-pipeline:
    apiEndpoints: [analytics]
    policies:
      - cors:  [ { action: *corsSettings } ]
      - proxy:
          - action:
              <<: *proxySettings
              serviceEndpoint: analytics-service
